name: uncertainty
channels:
  - defaults
dependencies:
  - python=3.9
  - torchvision
  - pytorch=1
  - pillow
  - matplotlib
  - scikit-learn
  - ipykernel 
  - tqdm
  - pip:
    - ipywidgets
    - albumentations
    - mayavi
    - dask
    - wandb
    - SciencePlots
    - fitter
    - scikit-image
    - SimpleITK
    - antspyx